<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SistemaAutobuses.Entidades\SistemaAutobuses.Entidades.csproj" />
    <ProjectReference Include="..\SistemaAutobuses.Datos\SistemaAutobuses.Datos.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
